%% Create New Tracks
% Adapted from PedestrianTrackingFromMovingCameraExample, 2014 The MathWorks, Inc.

function tracks = createNewTracks(tracks, unassignedDetections, centroids, bboxes, scores, nextId)

unassignedCentroids = centroids(unassignedDetections, :);
unassignedBboxes = bboxes(unassignedDetections, :);
unassignedScores = scores(unassignedDetections);

for i = 1:size(unassignedBboxes, 1)
    centroid = unassignedCentroids(i,:);
    bbox = unassignedBboxes(i, :);
    score = unassignedScores(i);
    
    % Create a Kalman filter object.
    kalmanFilter = configureKalmanFilter('ConstantVelocity', ...
        centroid, [2, 1], [5, 5], 100);
    
    % Create a new track.
    newTrack = struct(...
        'id', nextId, ...
        'color', 255*rand(1,3), ...
        'bboxes', bbox, ...
        'scores', score, ...
        'kalmanFilter', kalmanFilter, ...
        'age', 1, ...
        'totalVisibleCount', 1, ...
        'confidence', [score, score], ...
        'predPosition', bbox);
    
    % Add it to the array of tracks.
    tracks(end + 1) = newTrack; %#ok<AGROW>
end